# Generated by Django 5.1 on 2024-08-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_email', models.EmailField(max_length=254)),
                ('user_name', models.CharField(max_length=20)),
                ('user_nickname', models.CharField(max_length=20, unique=True)),
                ('profile_img', models.TimeField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
