# Generated by Django 5.1 on 2024-09-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_rename_user_id_feed_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='user_email',
            field=models.EmailField(max_length=254),
        ),
    ]
