# Generated by Django 5.1 on 2024-09-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_feed_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='user_email',
            field=models.TextField(),
        ),
    ]
